language: ruby
install:
  - bundle
cache: bundler
branches:
  only:
    - master
script: bundle exec jekyll build # or  - JEKYLL_ENV=production bundle exec jekyll build --destination site

deploy:
  provider: pages
  local-dir: ./_site
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master






#env:
#  global:
#s    - secure: ...

# script:
#   - jgd -u git@github.com:newamericafoundation/pandemicresponserepository.git
