language: ruby
before_install:
  - gem install bundler
#install:
#  - gem install bundler -v 2.1.4
#  - bundle
#  - bundle install
#  - gem install jekyll
branches:
  only:
    - master
script: bundle exec jekyll build
cache: bundler

deploy:
  provider: pages
  local-dir: ./_site
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master