language: ruby
before_install:
  - gem install bundler
branches:
  only:
    - master
script: wget -O _data/projects.csv $DATA_URL && bundle exec jekyll build
cache: bundler

env:
  global:
    - DATA_URL="https://docs.google.com/spreadsheets/d/e/2PACX-1vQ_b1JHv2liFqe3O11xqSd1toMoIdGMwq9F1M4Uz1f9VhQIufsBvGveBxWVstvrZgp9lKqUgtLRLvQQ/pub?gid=0&single=true&output=csv"

deploy:
  provider: pages
  local-dir: ./_site
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master