language: ruby
before_install:
  - gem install bundler
branches:
  only:
    - master
script: echo $CSV_LINK; wget -O _data/projects.csv $CSV_LINK && bundle exec jekyll build
cache: bundler

deploy:
  provider: pages
  local-dir: ./_site
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master